# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: FaceDetectionResult.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='FaceDetectionResult.proto',
  package='',
  syntax='proto2',
  serialized_pb=_b('\n\x19\x46\x61\x63\x65\x44\x65tectionResult.proto\"2\n\x04Rect\x12\t\n\x01x\x18\x01 \x02(\x05\x12\t\n\x01y\x18\x02 \x02(\x05\x12\t\n\x01w\x18\x03 \x02(\x05\x12\t\n\x01h\x18\x04 \x02(\x05\"0\n\x04Pose\x12\x0c\n\x04roll\x18\x01 \x02(\x02\x12\x0b\n\x03yaw\x18\x02 \x02(\x02\x12\r\n\x05pitch\x18\x03 \x02(\x02\"U\n\tFaceShape\x12\r\n\x01x\x18\x01 \x03(\x02\x42\x02\x10\x01\x12\r\n\x01y\x18\x02 \x03(\x02\x42\x02\x10\x01\x12\x16\n\nvisibility\x18\x03 \x03(\x02\x42\x02\x10\x01\x12\x12\n\nconfidence\x18\x04 \x02(\x02\"\xb2\x02\n\x04\x46\x61\x63\x65\x12\x13\n\x04rect\x18\x01 \x02(\x0b\x32\x05.Rect\x12\x19\n\x05shape\x18\x02 \x01(\x0b\x32\n.FaceShape\x12\x13\n\x04pose\x18\x03 \x01(\x0b\x32\x05.Pose\x12\x12\n\nconfidence\x18\x04 \x02(\x02\x12\x16\n\x0enameConfidence\x18\t \x01(\x02\x12\x0c\n\x04name\x18\n \x01(\t\x12\x0b\n\x03\x61ge\x18\x0b \x01(\x05\x12&\n\nproperties\x18\x0c \x03(\x0e\x32\x12.Face.FaceProperty\x12\x1c\n\x06gender\x18\r \x01(\x0e\x32\x0c.Face.Gender\x12\r\n\x05\x61live\x18\x0e \x01(\x08\",\n\x0c\x46\x61\x63\x65Property\x12\t\n\x05GLASS\x10\x00\x12\x08\n\x04MASK\x10\x01\x12\x07\n\x03HAT\x10\x02\"\x1b\n\x06Gender\x12\x08\n\x04GIRL\x10\x00\x12\x07\n\x03\x42OY\x10\x01\"I\n\x13\x46\x61\x63\x65\x44\x65tectionResult\x12\r\n\x05width\x18\x01 \x02(\x05\x12\x0e\n\x06height\x18\x02 \x02(\x05\x12\x13\n\x04\x66\x61\x63\x65\x18\x03 \x03(\x0b\x32\x05.Face')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)



_FACE_FACEPROPERTY = _descriptor.EnumDescriptor(
  name='FaceProperty',
  full_name='Face.FaceProperty',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='GLASS', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='MASK', index=1, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='HAT', index=2, number=2,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=452,
  serialized_end=496,
)
_sym_db.RegisterEnumDescriptor(_FACE_FACEPROPERTY)

_FACE_GENDER = _descriptor.EnumDescriptor(
  name='Gender',
  full_name='Face.Gender',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='GIRL', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='BOY', index=1, number=1,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=498,
  serialized_end=525,
)
_sym_db.RegisterEnumDescriptor(_FACE_GENDER)


_RECT = _descriptor.Descriptor(
  name='Rect',
  full_name='Rect',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='x', full_name='Rect.x', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='y', full_name='Rect.y', index=1,
      number=2, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='w', full_name='Rect.w', index=2,
      number=3, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='h', full_name='Rect.h', index=3,
      number=4, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=29,
  serialized_end=79,
)


_POSE = _descriptor.Descriptor(
  name='Pose',
  full_name='Pose',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='roll', full_name='Pose.roll', index=0,
      number=1, type=2, cpp_type=6, label=2,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='yaw', full_name='Pose.yaw', index=1,
      number=2, type=2, cpp_type=6, label=2,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='pitch', full_name='Pose.pitch', index=2,
      number=3, type=2, cpp_type=6, label=2,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=81,
  serialized_end=129,
)


_FACESHAPE = _descriptor.Descriptor(
  name='FaceShape',
  full_name='FaceShape',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='x', full_name='FaceShape.x', index=0,
      number=1, type=2, cpp_type=6, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=_descriptor._ParseOptions(descriptor_pb2.FieldOptions(), _b('\020\001'))),
    _descriptor.FieldDescriptor(
      name='y', full_name='FaceShape.y', index=1,
      number=2, type=2, cpp_type=6, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=_descriptor._ParseOptions(descriptor_pb2.FieldOptions(), _b('\020\001'))),
    _descriptor.FieldDescriptor(
      name='visibility', full_name='FaceShape.visibility', index=2,
      number=3, type=2, cpp_type=6, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=_descriptor._ParseOptions(descriptor_pb2.FieldOptions(), _b('\020\001'))),
    _descriptor.FieldDescriptor(
      name='confidence', full_name='FaceShape.confidence', index=3,
      number=4, type=2, cpp_type=6, label=2,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=131,
  serialized_end=216,
)


_FACE = _descriptor.Descriptor(
  name='Face',
  full_name='Face',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='rect', full_name='Face.rect', index=0,
      number=1, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='shape', full_name='Face.shape', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='pose', full_name='Face.pose', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='confidence', full_name='Face.confidence', index=3,
      number=4, type=2, cpp_type=6, label=2,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='nameConfidence', full_name='Face.nameConfidence', index=4,
      number=9, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='name', full_name='Face.name', index=5,
      number=10, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='age', full_name='Face.age', index=6,
      number=11, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='properties', full_name='Face.properties', index=7,
      number=12, type=14, cpp_type=8, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='gender', full_name='Face.gender', index=8,
      number=13, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='alive', full_name='Face.alive', index=9,
      number=14, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _FACE_FACEPROPERTY,
    _FACE_GENDER,
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=219,
  serialized_end=525,
)


_FACEDETECTIONRESULT = _descriptor.Descriptor(
  name='FaceDetectionResult',
  full_name='FaceDetectionResult',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='width', full_name='FaceDetectionResult.width', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='height', full_name='FaceDetectionResult.height', index=1,
      number=2, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='face', full_name='FaceDetectionResult.face', index=2,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=527,
  serialized_end=600,
)

_FACE.fields_by_name['rect'].message_type = _RECT
_FACE.fields_by_name['shape'].message_type = _FACESHAPE
_FACE.fields_by_name['pose'].message_type = _POSE
_FACE.fields_by_name['properties'].enum_type = _FACE_FACEPROPERTY
_FACE.fields_by_name['gender'].enum_type = _FACE_GENDER
_FACE_FACEPROPERTY.containing_type = _FACE
_FACE_GENDER.containing_type = _FACE
_FACEDETECTIONRESULT.fields_by_name['face'].message_type = _FACE
DESCRIPTOR.message_types_by_name['Rect'] = _RECT
DESCRIPTOR.message_types_by_name['Pose'] = _POSE
DESCRIPTOR.message_types_by_name['FaceShape'] = _FACESHAPE
DESCRIPTOR.message_types_by_name['Face'] = _FACE
DESCRIPTOR.message_types_by_name['FaceDetectionResult'] = _FACEDETECTIONRESULT

Rect = _reflection.GeneratedProtocolMessageType('Rect', (_message.Message,), dict(
  DESCRIPTOR = _RECT,
  __module__ = 'FaceDetectionResult_pb2'
  # @@protoc_insertion_point(class_scope:Rect)
  ))
_sym_db.RegisterMessage(Rect)

Pose = _reflection.GeneratedProtocolMessageType('Pose', (_message.Message,), dict(
  DESCRIPTOR = _POSE,
  __module__ = 'FaceDetectionResult_pb2'
  # @@protoc_insertion_point(class_scope:Pose)
  ))
_sym_db.RegisterMessage(Pose)

FaceShape = _reflection.GeneratedProtocolMessageType('FaceShape', (_message.Message,), dict(
  DESCRIPTOR = _FACESHAPE,
  __module__ = 'FaceDetectionResult_pb2'
  # @@protoc_insertion_point(class_scope:FaceShape)
  ))
_sym_db.RegisterMessage(FaceShape)

Face = _reflection.GeneratedProtocolMessageType('Face', (_message.Message,), dict(
  DESCRIPTOR = _FACE,
  __module__ = 'FaceDetectionResult_pb2'
  # @@protoc_insertion_point(class_scope:Face)
  ))
_sym_db.RegisterMessage(Face)

FaceDetectionResult = _reflection.GeneratedProtocolMessageType('FaceDetectionResult', (_message.Message,), dict(
  DESCRIPTOR = _FACEDETECTIONRESULT,
  __module__ = 'FaceDetectionResult_pb2'
  # @@protoc_insertion_point(class_scope:FaceDetectionResult)
  ))
_sym_db.RegisterMessage(FaceDetectionResult)


_FACESHAPE.fields_by_name['x'].has_options = True
_FACESHAPE.fields_by_name['x']._options = _descriptor._ParseOptions(descriptor_pb2.FieldOptions(), _b('\020\001'))
_FACESHAPE.fields_by_name['y'].has_options = True
_FACESHAPE.fields_by_name['y']._options = _descriptor._ParseOptions(descriptor_pb2.FieldOptions(), _b('\020\001'))
_FACESHAPE.fields_by_name['visibility'].has_options = True
_FACESHAPE.fields_by_name['visibility']._options = _descriptor._ParseOptions(descriptor_pb2.FieldOptions(), _b('\020\001'))
# @@protoc_insertion_point(module_scope)
