# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: FilePart.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='FilePart.proto',
  package='',
  syntax='proto2',
  serialized_pb=_b('\n\x0e\x46ilePart.proto\"K\n\x08\x46ilePart\x12\x0c\n\x04path\x18\x01 \x02(\t\x12\x13\n\x0btotalLength\x18\x02 \x02(\x05\x12\x0e\n\x06offset\x18\x03 \x02(\x05\x12\x0c\n\x04\x64\x61ta\x18\x04 \x02(\x0c')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_FILEPART = _descriptor.Descriptor(
  name='FilePart',
  full_name='FilePart',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='path', full_name='FilePart.path', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='totalLength', full_name='FilePart.totalLength', index=1,
      number=2, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='offset', full_name='FilePart.offset', index=2,
      number=3, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='data', full_name='FilePart.data', index=3,
      number=4, type=12, cpp_type=9, label=2,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=18,
  serialized_end=93,
)

DESCRIPTOR.message_types_by_name['FilePart'] = _FILEPART

FilePart = _reflection.GeneratedProtocolMessageType('FilePart', (_message.Message,), dict(
  DESCRIPTOR = _FILEPART,
  __module__ = 'FilePart_pb2'
  # @@protoc_insertion_point(class_scope:FilePart)
  ))
_sym_db.RegisterMessage(FilePart)


# @@protoc_insertion_point(module_scope)
