# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: RegisterFaceIdWithPicParams.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='RegisterFaceIdWithPicParams.proto',
  package='',
  syntax='proto2',
  serialized_pb=_b('\n!RegisterFaceIdWithPicParams.proto\"?\n\x1bRegisterFaceIdWithPicParams\x12\x0e\n\x06\x66\x61\x63\x65Id\x18\x01 \x02(\t\x12\x10\n\x08\x66ilePath\x18\x02 \x02(\t')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_REGISTERFACEIDWITHPICPARAMS = _descriptor.Descriptor(
  name='RegisterFaceIdWithPicParams',
  full_name='RegisterFaceIdWithPicParams',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='faceId', full_name='RegisterFaceIdWithPicParams.faceId', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='filePath', full_name='RegisterFaceIdWithPicParams.filePath', index=1,
      number=2, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=37,
  serialized_end=100,
)

DESCRIPTOR.message_types_by_name['RegisterFaceIdWithPicParams'] = _REGISTERFACEIDWITHPICPARAMS

RegisterFaceIdWithPicParams = _reflection.GeneratedProtocolMessageType('RegisterFaceIdWithPicParams', (_message.Message,), dict(
  DESCRIPTOR = _REGISTERFACEIDWITHPICPARAMS,
  __module__ = 'RegisterFaceIdWithPicParams_pb2'
  # @@protoc_insertion_point(class_scope:RegisterFaceIdWithPicParams)
  ))
_sym_db.RegisterMessage(RegisterFaceIdWithPicParams)


# @@protoc_insertion_point(module_scope)
